// projects/ng-mdx-remote-demo/src/app/rc-mdx-components/AlertBox.tsx
import React from 'react';

// Define props interface
interface AlertBoxProps {
  message: string;
  type?: 'info' | 'warning' | 'error';
}

// Define the AlertBox component
const AlertBox: React.FC<AlertBoxProps> = ({ message, type = 'info' }) => {
  const alertStyles = {
    info: { backgroundColor: '#e7f0ff', color: '#0056b3' },
    warning: { backgroundColor: '#fff3cd', color: '#856404' },
    error: { backgroundColor: '#f8d7da', color: '#721c24' }
  };

  return (
    <div 
      style={{ 
        padding: '10px', 
        borderRadius: '4px', 
        border: `1px solid ${alertStyles[type].color}`, 
        backgroundColor: alertStyles[type].backgroundColor, 
        color: alertStyles[type].color
      }}
    >
      {message}
    </div>
  );
};

export default AlertBox;

// projects/ng-mdx-remote-demo/src/app/ng-mdx-components/ng-alert-box.component.ts
import { Component, Input } from '@angular/core';
import {CommonModule} from '@angular/common'

@Component({
  selector: 'ng-alert-box',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './ng-alert-box.component.html',
  styleUrls: ['./ng-alert-box.component.css']
})
export class ng_AlertBoxComponent {
  @Input() message!: string;
  @Input() type: 'info' | 'warning' | 'error' = 'info';

  get alertStyles() {
    return {
      info: { backgroundColor: '#e7f0ff', color: '#0056b3' },
      warning: { backgroundColor: '#fff3cd', color: '#856404' },
      error: { backgroundColor: '#f8d7da', color: '#721c24' }
    }[this.type];
  }
}
<div [ngStyle]="{ 
    padding: '10px', 
    borderRadius: '4px', 
    border: '1px solid ' + alertStyles.color, 
    backgroundColor: alertStyles.backgroundColor, 
    color: alertStyles.color 
  }">
  {{ message }}
</div>
